version: '3'

services:
  green-container:
    container_name: 'zokboo-backend-green'
    image: hooo0503/zokboo-dev:green
    env_file:
      - /build/backend/.env
    ports:
      - '13371:8080'

networks:
  default:

volumes:
  green-container: