version: '3'

services:
  blue-container:
    container_name: 'zokboo-backend-blue'
    image: hooo0503/zokboo-dev:blue
    env_file:
      - /build/backend/.env
    ports:
      - '13370:8080'

networks:
  default:

volumes:
  blue-container: