version: '3'

services:
  green-container:
    container_name: 'zokboo-frontend-green'
    image: heroleggo/zokboo-front:green
    env_file:
      - /build/frontend/.env
    ports:
      - '29494:3000'

networks:
  default:

volumes:
  green-container: