name: "[Backend] develop CI/CD"
on:
  push:
    branches: ["develop"]
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p  ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t zokboo-dev ./server/
          docker image tag zokboo-dev hooo0503/zokboo-dev:blue
          docker image tag zokboo-dev hooo0503/zokboo-dev:green
          docker image push -a hooo0503/zokboo-dev

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          script: /build/backend/deploy-blue-green.sh
