on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_PROD_IP }}
          username: ${{ secrets.REMOTE_PROD_SSH_ID }}
          key: ${{ secrets.REMOTE_PROD_SSH_KEY }}
          port: ${{ secrets.REMOTE_PROD_SSH_PORT }}
          script: |
            cd web07-zokboo.com
            git pull
            npm install
            pm2 restart 0
