name: "[Frontend] develop CI/CD"
on:
  push:
    branches: ["develop"]
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: |
          docker login -u ${{ secrets.FRONTEND_DOCKERHUB_USERNAME }} -p ${{ secrets.FRONTEND_DOCKERHUB_PASSWORD }}
          docker build -t zokboo-front-dev --build-arg SERVER_URL=${{ secrets.SERVER_URL }} ./client/
          docker image tag zokboo-front-dev heroleggo/zokboo-front:blue
          docker image tag zokboo-front-dev heroleggo/zokboo-front:green
          docker image push -a heroleggo/zokboo-front

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          script: /build/frontend/deploy-blue-green.sh
