name: "[Frontend] production CI/CD"
on:
  push:
    branches: ["main"]
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Docker Build - Production
        run: |
          docker login -u ${{ secrets.FRONTEND_DOCKERHUB_USERNAME }} -p ${{ secrets.FRONTEND_DOCKERHUB_PASSWORD }}
          docker build -t zokboo-front-prod \
            --build-arg SSO_URL=${{ secrets.REACT_APP_SSO_URL }} \
            --build-arg SERVER_URL=${{ secrets.SERVER_URL }} \
            --build-arg GITHUB=${{ secrets.REACT_APP_GITHUB }} \
            --build-arg NAVER=${{ secrets.REACT_APP_NAVER }} \
            --build-arg GOOGLE=${{ secrets.REACT_APP_GOOGLE }} \
            --build-arg KAKAO=${{ secrets.REACT_APP_KAKAO }} \
            ./client/
          docker image tag zokboo-front-prod heroleggo/zokboo-front-prod:blue
          docker image tag zokboo-front-prod heroleggo/zokboo-front-prod:green
          docker image push -a heroleggo/zokboo-front-prod

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          password: ${{ secrets.PROD_SERVER_PASSWORD }}
          script: /build/frontend/deploy-blue-green.sh